# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.setWindowModality(QtCore.Qt.WindowModal)
        AboutDialog.resize(357, 93)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAppName = QtWidgets.QLabel(AboutDialog)
        self.labelAppName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAppName.setObjectName("labelAppName")
        self.verticalLayout.addWidget(self.labelAppName)
        self.labelCopy = QtWidgets.QLabel(AboutDialog)
        self.labelCopy.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCopy.setObjectName("labelCopy")
        self.verticalLayout.addWidget(self.labelCopy)
        self.labelWeb = QtWidgets.QLabel(AboutDialog)
        self.labelWeb.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWeb.setObjectName("labelWeb")
        self.verticalLayout.addWidget(self.labelWeb)
        self.labelLicense = QtWidgets.QLabel(AboutDialog)
        self.labelLicense.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLicense.setWordWrap(True)
        self.labelLicense.setObjectName("labelLicense")
        self.verticalLayout.addWidget(self.labelLicense)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.labelAppName.setText(_translate("AboutDialog", "Ham Radio Applications Manager - Version 1.0"))
        self.labelCopy.setText(_translate("AboutDialog", "(c) 2025, I8ZSE Giorgio L. Rutigliano"))
        self.labelWeb.setText(_translate("AboutDialog", "https://www.i8zse.it - https://github.com/grutig"))
        self.labelLicense.setText(_translate("AboutDialog", "This application is licensed under the LGPL v3 license."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutDialog = QtWidgets.QDialog()
    ui = Ui_AboutDialog()
    ui.setupUi(AboutDialog)
    AboutDialog.show()
    sys.exit(app.exec_())
